name: benchmark

on:
  push:
    branches:
      - ci-benchmark

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y && sudo apt install -y pandoc tabix bcftools libhts-dev
      - name: Cache VCF
        id: cache-vcf
        uses: actions/cache@v3
        with:
          path: |
            1kg.chr1.subset.vcf.gz
            1kg.chr1.subset.bcf
          key: ${{ runner.os }}-vcf
      - name: Download and prepare test data
        if: steps.cache-vcf.outputs.cache-hit != 'true'
        run: |
          wget -O - http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_raw_GT_with_annot/20201028_CCDG_14151_B01_GRM_WGS_2020-08-05_chr1.recalibrated_variants.vcf.gz | zcat - | head -30000 | bgzip -c > 1kg.chr1.subset.vcf.gz
          bcftools view -O b 1kg.chr1.subset.vcf.gz > 1kg.chr1.subset.bcf
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          : # cargo install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.13.0/hyperfine_1.13.0_amd64.deb
          sudo apt install -y ./hyperfine_1.13.0_amd64.deb
      - uses: crystal-lang/install-crystal@v1
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble install -y hts
      - run: pip3 install cyvcf2
      - run: pip3 install pysam
      - run: cd c-htslib && make
      - run: cd crystal-htslibcr && make
      - run: cd nim-hts-nim && nim compile -d:release read.nim 
      - run: cd rust-htslib && cargo build --release
      - run: ./run.sh
      - name: Generate HTML
        run: cd result && pandoc vcf-bench.md -o index.html
      - name: Output results to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
