name: benchmark

on:
  push:
    branches:
      - ci-benchmark

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y && sudo apt install -y tabix bcftools
      - name: Cache VCF
        id: cache-vcf
        uses: actions/cache@v3
        with:
          path: 1kg.chr1.subset.vcf.gz
          key: ${{ runner.os }}-primes
      - name: Download test data
        if: steps.cache-vcf.outputs.cache-hit != 'true'
        run: wget -O - http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_raw_GT_with_annot/20201028_CCDG_14151_B01_GRM_WGS_2020-08-05_chr1.recalibrated_variants.vcf.gz | zcat - | head -30000 | bgzip -c > 1kg.chr1.subset.vcf.gz
